"""Core data types for GhostSIEM."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class Severity(str, Enum):
    """Event and alert severity levels."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

    @classmethod
    def from_string(cls, value: str) -> Severity:
        """Parse a severity string, case-insensitive."""
        mapping = {
            "low": cls.LOW,
            "informational": cls.LOW,
            "info": cls.LOW,
            "medium": cls.MEDIUM,
            "high": cls.HIGH,
            "critical": cls.CRITICAL,
        }
        return mapping.get(value.lower(), cls.LOW)


@dataclass
class Event:
    """Normalized security event."""

    timestamp: datetime
    source: str
    hostname: str
    severity: Severity
    message: str
    raw: str
    parsed_fields: dict[str, Any] = field(default_factory=dict)
    id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def to_dict(self) -> dict[str, Any]:
        """Serialize event to a dictionary."""
        return {
            "id": self.id,
            "timestamp": self.timestamp.isoformat(),
            "source": self.source,
            "hostname": self.hostname,
            "severity": self.severity.value,
            "message": self.message,
            "raw": self.raw,
            "parsed_fields": self.parsed_fields,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Event:
        """Deserialize event from a dictionary."""
        return cls(
            id=data.get("id", str(uuid.uuid4())),
            timestamp=datetime.fromisoformat(data["timestamp"]),
            source=data["source"],
            hostname=data.get("hostname", "unknown"),
            severity=Severity.from_string(data.get("severity", "low")),
            message=data["message"],
            raw=data.get("raw", data["message"]),
            parsed_fields=data.get("parsed_fields", {}),
        )


@dataclass
class Alert:
    """Security alert generated by a detection rule."""

    rule_id: str
    rule_name: str
    severity: Severity
    event: Event
    timestamp: datetime
    description: str
    id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def to_dict(self) -> dict[str, Any]:
        """Serialize alert to a dictionary."""
        return {
            "id": self.id,
            "rule_id": self.rule_id,
            "rule_name": self.rule_name,
            "severity": self.severity.value,
            "event": self.event.to_dict(),
            "timestamp": self.timestamp.isoformat(),
            "description": self.description,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Alert:
        """Deserialize alert from a dictionary."""
        return cls(
            id=data.get("id", str(uuid.uuid4())),
            rule_id=data["rule_id"],
            rule_name=data["rule_name"],
            severity=Severity.from_string(data.get("severity", "low")),
            event=Event.from_dict(data["event"]),
            timestamp=datetime.fromisoformat(data["timestamp"]),
            description=data["description"],
        )


def now_utc() -> datetime:
    """Return the current UTC datetime."""
    return datetime.now(timezone.utc)
